INSERT INTO event_type (event_type_code, label) values ('1', 'Contraindication - Allergy Previous Dose'); -- Contraindications - Allergy Previous Dose
INSERT INTO event_type (event_type_code, label) values ('2', 'Contraindication - Allergy Vaccine Component'); -- Contraindications - Allergy Vaccine Component
INSERT INTO event_type (event_type_code, label) values ('3', 'Contraindication - Risk Factor'); -- Contraindications - Risk Factor
INSERT INTO event_type (event_type_code, label) values ('4', 'Contraindication - Unspecified'); -- Contraindications - Unspecified
INSERT INTO event_type (event_type_code, label) values ('I', 'Immunity'); -- Immunities
INSERT INTO event_type (event_type_code, label) values ('P', 'Precaution'); -- Precautions
INSERT INTO event_type (event_type_code, label) values ('R', 'Refusal'); -- Refusals
INSERT INTO event_type (event_type_code, label) values ('E', 'Religious Exemption'); -- Religious exemptions
INSERT INTO event_type (event_type_code, label) values ('S', 'Special Indication'); -- Special Indications

INSERT INTO event (event_id, label, event_type_code) VALUES (100032, 'Adeno T4', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100033, 'Adeno T7', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100034, 'Anthrax', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100035, 'BCG-BC', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100036, 'BCG-TB', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100037, 'Botulinum-antitoxin', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100039, 'CMV-IgIV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100040, 'Cholera-Inject', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100041, 'Cholera-Oral', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100042, 'DT-Peds', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100043, 'DTaP-HepB-IPV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100044, 'DTP', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100045, 'DTP-Hib', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100046, 'DTaP', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100047, 'DTaP  5 pertussis antigens', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100048, 'DTaP-Hib', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100049, 'Diphtheria', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100283, 'MCV4  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100050, 'Diphtheria-antitoxin', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100051, 'HBIg', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100052, 'HepA-Adult', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100053, 'HepA-HepB Adult', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100054, 'HepA-Ped 2 Dose', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100055, 'HepA-Peds', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100056, 'HepA-Unspecified', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100057, 'HepB adolescent- 2 dose', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100058, 'HepB-Adult', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100059, 'HepB-Dialysis 3 dose', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100060, 'HepB-Dialysis 4 dose', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100284, 'HepB-Unspecified', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100061, 'HepB-Hib', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100062, 'HepB-Peds', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100285, 'Hib Unspecified', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100063, 'Hib-HbOC', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100064, 'Hib-OMP', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100065, 'Hib-PRP-D', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100066, 'Hib-PRP-T', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100067, 'Flu Unspecified', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100068, 'FLU-LAIV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100070, 'Japanese Encephalitis -IM (IXARO)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100071, 'Lyme', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100072, 'MMR', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100073, 'MMRV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100074, 'Measles', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100075, 'Measles-Rubella', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100286, 'Mumps', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100287, 'Rubella-Mumps', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100076, 'MPSV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100289, 'Meningococcal Unspecified', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100078, 'Plague', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100079, 'PCV7', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100080, 'Pneumococcal 23', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100081, 'Polio-Inject', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100082, 'Polio-Oral', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100083, 'RIg', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100084, 'RIg-HT', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100085, 'RSV-IgIM', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100086, 'RSV-IgIV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100087, 'Rabies-ID', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100088, 'Rabies  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100089, 'Rho(D)Full', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100090, 'Rho(D)IV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100091, 'Rho(D)Mini', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100092, 'Rotavirus  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100093, 'Rubella', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100095, 'Vaccinia (smallpox)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100096, 'TIg', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100290, 'Td (preservative free)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100097, 'Td', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100098, 'Tetanus toxoid  adsorbed', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100099, 'Typhoid-AKD', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100100, 'Typhoid-HP', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100101, 'Typhoid-Oral', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100102, 'Typhoid-ViCPs', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100103, 'VZIg', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100104, 'Vaccinia (smallpox)  diluted', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100105, 'Vaccinia immune globulin VIG', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100106, 'Varicella', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100107, 'Yellow Fever', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100291, 'HZV (zoster)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100273, 'HPV  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100315, 'DTaP-Hib-IPV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100316, 'DTaP-IPV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100317, 'HPV bivalent', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100318, 'PCV13', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100324, 'Tdap', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100325, 'FLU-TIV (inactivated  T-containing or Preservative-free)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101339, 'VZIG (IND)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101340, 'Typhus  Historical', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101341, 'yphoid  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101342, 'Tick Borne Encephalitis ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101343, 'Tetanus toxoid  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101344, 'Tetanus toxoid  not adsorbed', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101345, 'Td unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101346, 'Td (not adsorbed)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101347, 'RSV-Mab', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101348, 'Rift Valley Fever', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101349, 'Rheumatic Fever ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101350, 'Q fever', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101351, 'Polio  Unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101352, 'Pneumococcal  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101353, 'Pertussis ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101354, 'Parainfluenza-3 ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101355, 'Meningococcal C', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101356, 'Melanoma ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101357, 'MCV-Menveo', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101358, 'MCV-Menactra', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101359, 'Malaria ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101360, 'Leprosy ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101361, 'Leishmaniasis ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101362, 'Junin Virus ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101363, 'Japanese Encephalitis unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101364, 'Japanese Encephalitis -SC (JE-VAX)', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101365, 'IgIV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101366, 'IG  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101367, 'Ig', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101368, 'HIV ', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101369, 'Hep E', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101370, 'Hep C', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101371, 'HepA-Peds  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101372, 'Flu-TIV-ID', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101373, 'Flu-TIV  whole virus', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101374, 'Flu-TIV >= 3 yrs', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101375, 'Flu-High Dose', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101376, 'Flu-H5N1-unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101377, 'Flu-H5N1', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101378, 'Flu-H1N1-preservative-free >=3 yrs', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101379, 'Flu-H1N1-LAIV', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101380, 'Flu-H1N1 6-35 mos', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101381, 'Flu-H1N1 >=3yrs', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101382, 'DTaP-IPV-HepB-Hib  historical', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101383, 'DTaP-IPV-HepB-Hib', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101384, 'DTaP  unspecified', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (101385, 'Adenovirus  unspecified formulation', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (102731, 'HPV quadrivalent', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100882, 'Rabies-IM', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100923, 'Rotavirus  monovalent', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100924, 'Rotavirus  pentavalent', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100925, 'Rotavirus  tetravalent', '1');
INSERT INTO event (event_id, label, event_type_code) VALUES (100019, 'proteins of rodent or neural origin', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100280, 'formaldehyde/formalin', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100020, '2-phenoxyethanol', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100021, 'alum  aluminum hydroxide  aluminum hydroxyphosphate sulfate  aluminum phosphate  aluminum potassium sulfate', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100022, 'yeast protein', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100023, 'chlortetracycline', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100025, 'gelatin', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100026, 'latex', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100027, 'neomycin', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100028, 'polymyxin B', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100029, 'streptomycin', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100030, 'thimerosal', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100274, 'fetal bovine serum', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100328, 'gentamicin', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100361, 'severe reaction (anaphylaxis) to egg protein. ', '2');
INSERT INTO event (event_id, label, event_type_code) VALUES (100001, 'antibiotics', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100003, 'aspirin or salicylate therapy', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100004, 'breast feeding', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100005, 'chronic illness (e.g. chronic lung  cardiac disease)', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100006, 'encephalopathy within 7 days of previous dose of DTP or DTaP', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100007, 'heart condition', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100008, 'immunodeficiency (mild) in recipient', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100009, 'immunodeficiency (severe) in household contact due to any cause', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100010, 'immunodeficiency (severe) in household contact during time in protective environment', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100011, 'immunodeficiency (severe) in recipient due to any cause', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100279, 'high-dose steroid use for >14 days within the past month.', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100012, 'pregnancy (in household contacts)', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100013, 'pregnancy (in recipient)', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100015, 'skin condition (acute  chronic or exfoliative) in household contacts', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100016, 'skin condition (acute  chronic or exfoliative) in recipient', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100017, 'steroid eye drops', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100018, 'tuberculosis (active)', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100276, 'previous history of intussusception', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100329, 'wheezing in the previous 12 months for children 2-4 years of age', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100330, 'immunodeficiency (severe combined immunodeficiency)', '3');
INSERT INTO event (event_id, label, event_type_code) VALUES (100128, 'previous dose of HepA-Adult', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100129, 'previous dose of HepA-HepB Adult', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100130, 'previous dose of HepA-Ped 2 Dose', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100131, 'previous dose of HepA-Peds', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100132, 'previous dose of HepA-Unspecified', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100133, 'previous dose of HepB adolescent- 2 dose', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100134, 'previous dose of HepB-Adult', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100135, 'previous dose of HepB-Dialysis 3 dose', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100136, 'previous dose of HepB-Dialysis 4 dose', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100137, 'previous dose of HepB-Hib', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100138, 'previous dose of HepB-Peds', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100139, 'previous dose of Hib-HbOC', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100140, 'previous dose of Hib-OMP', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100141, 'previous dose of Hib-PRP-D', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100142, 'previous dose of Hib-PRP-T', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100281, 'previous dose of HPV bivalent', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100143, 'previous dose of Flu Unspecified', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100144, 'previous dose of FLU-LAIV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100145, 'previous dose of FLU-TIV (inactivated  preservative-free)', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100108, 'previous dose of Adeno T4', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100109, 'previous dose of Adeno T7', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100110, 'previous dose of Anthrax', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100111, 'previous dose of BCG-BC', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100112, 'previous dose of BCG-TB', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100113, 'previous dose of Botulinum-antitoxin', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100115, 'previous dose of CMV-IgIV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100116, 'previous dose of Cholera-Inject', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100117, 'previous dose of Cholera-Oral', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100118, 'previous dose of DT-Peds', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100119, 'previous dose of DTaP-HepB-IPV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100120, 'previous dose of DTP', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100121, 'previous dose of DTP-Hib', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100122, 'previous dose of DTaP', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100123, 'previous dose of DTaP 5 pertussis antigens', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100124, 'previous dose of DTaP-Hib', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100125, 'previous dose of Diphtheria', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100292, 'previous dose of Tdap', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100126, 'previous dose of Diphtheria-antitoxin', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100127, 'previous dose of HBIg', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100146, 'previous dose of Japanese Encephalitis', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100147, 'previous dose of Lyme', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100148, 'previous dose of MMR', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100149, 'previous dose of MMRV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100150, 'previous dose of Measles', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100151, 'previous dose of Measles-Rubella', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100153, 'previous dose of Mumps', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100293, 'previous dose of Rubella-Mumps', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100077, 'previous dose of MPSV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100295, 'previous dose of Meningococcal Unspecified', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100154, 'previous dose of Plague', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100155, 'previous dose of PCV7', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100156, 'previous dose of Pneumococcal 23', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100157, 'previous dose of Polio-Inject', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100158, 'previous dose of Polio-Oral', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100159, 'previous dose of RIg', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100160, 'previous dose of RIg-HT', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100161, 'previous dose of RSV-IgIM', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100162, 'previous dose of RSV-IgIV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100163, 'previous dose of Rabies-ID', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100164, 'previous dose of Rabies-IM', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100165, 'previous dose of Rho(D)Full', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100166, 'previous dose of Rho(D)IV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100167, 'previous dose of Rho(D)Mini', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100168, 'previous dose of Rotavirus', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100169, 'previous dose of Rubella', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100296, 'previous dose of HZV (zoster)', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100172, 'previous dose of TIg', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100173, 'previous dose of Td', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100297, 'previous dose of Td (preservative free)', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100174, 'previous dose of Tetanus', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100175, 'previous dose of Typhoid-AKD', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100176, 'previous dose of Typhoid-HP', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100177, 'previous dose of Typhoid-Oral', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100178, 'previous dose of Typhoid-ViCPs', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100179, 'previous dose of VZIg', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100180, 'previous dose of Vaccinia (smallpox)  diluted', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100181, 'previous dose of Vaccinia immune globulin VIG', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100182, 'previous dose of Varicella', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100183, 'previous dose of Yellow Fever', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100319, 'previous dose of DTaP-Hib-IPV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100320, 'previous dose of DTaP-IPV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100321, 'previous dose of HPV quadrivalent', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100322, 'previous dose of PCV13', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100323, 'previous dose of Vaccinia (smallpox)', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100326, 'previous dose of MCV', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100327, 'previous dose of Hib Unspecified', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100354, 'previous dose of HepB-unspecified', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100282, 'previous dose of FLU-TIV vaccine', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100363, 'previous dose of Flu - unspecified', '4');
INSERT INTO event (event_id, label, event_type_code) VALUES (100198, 'diphtheria (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100200, 'Haemophilus influenza type B (Hib) (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100201, 'hepatitis A (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100202, 'hepatitis B (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100203, 'measles (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100204, 'mumps (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100207, 'polio (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100208, 'rubella (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100209, 'tetanus (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100210, 'Clinician-certified history of Varicella (chickenpox)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100211, 'Varicella (serologic)', 'I');
INSERT INTO event (event_id, label, event_type_code) VALUES (100002, 'antiviral drugs', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100014, 'prior infection with Anthrax', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100031, 'history of Anthrax infection', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100192, 'persistent  inconsolable crying lasting > 3 hours within 48 hours of previous dose of DTP/DTaP', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100193, 'steroids (high-dose for < 14 days)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100194, 'steroids (topical  aerosol  or local injections)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100195, 'thrombocytopenia', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100196, 'thrombocytopenia purpura (history)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100197, 'underlying unstable evolving neurologic disorders  (including seizure disorders  cerebral palsy and developmental delay)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100184, 'collapse or shock like state within 48 hours of previous dose of DTP/DTaP', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100185, 'convulsions (fits  seizures) within 72 hours of previous dose of DTP/DTaP', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100186, 'current moderate-to-severe illness (with or without fever)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100187, 'fever of >40.5C (105F) within 48 hours of previous dose of DTP/DTaP', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100188, 'Guillain-Barre syndrome (GBS) within 6 weeks of previous dose of DTP/DTaP', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100189, 'immunodeficiency (family history)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100190, 'immune globulin- containing blood product (recent or simultaneous)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100191, 'immunodeficiency (mild) in recipient', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100298, 'use of salicylates', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100299, 'history of Arthus hypersensitivity reaction to a tetanus-containing vaccine administered < 10 yrs previously', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100275, 'preexisting chronic gastrointestinal (GI) disease', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100277, 'recommended Rabies vaccine schedule not followed', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100331, 'history of Arthus hypersensitivity to a diphtheria containing vaccine', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100332, 'history of Guillain-Barre syndrome (GBS) within 6 weeks of a previous dose of influenza vaccine', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100334, 'progressive or unstable neurologic disorder  uncontrolled seizures or progressive encephalopathy', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100350, 'pregnancy', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (101337, 'allergy (egg ingestion and hives only)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (101338, 'history of Guillain-Barre syndrome (GBS)', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100371, 'Convulsions (fits or seizures) any cause - personal or family history', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100999, 'Test Comment Description Text', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100998, 'Test Comment with no IFM_ACTION text', 'P');
INSERT INTO event (event_id, label, event_type_code) VALUES (100238, 'all vaccines', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100239, 'Anthrax vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100240, 'DTaP vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100241, 'HepA vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100242, 'HepB vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100243, 'Hib vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100244, 'Flu vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100245, 'Japanese Encephalitis vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100246, 'Lyme vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100247, 'MMR vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100248, 'Measles vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100250, 'Meningococcal vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100251, 'Mumps vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100252, 'Pneumo-Conjugate vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100253, 'Pneumococcal Polysaccharide (PPSV23) vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100254, 'Polio vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100255, 'Rabies vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100256, 'Rotavirus vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100257, 'Rubella vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100260, 'Tetanus vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100261, 'Typhoid vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100262, 'Vaccinia (smallpox) vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100263, 'Vaccinia immune globulin', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100264, 'Varicella vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100265, 'Yellow Fever vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100266, 'Td vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100272, 'HPV vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100335, 'Tdap vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100336, 'MCV vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100337, 'MPSV vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100339, 'HZV (zoster) vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100340, 'DT vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100341, 'DTP vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100355, 'Rubella-Mumps vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100356, 'Measles-Rubella vaccine', 'R');
INSERT INTO event (event_id, label, event_type_code) VALUES (100217, 'all vaccines', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100218, 'Anthrax vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100219, 'DTaP vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100300, 'Tdap vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100220, 'DT', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100301, 'DTP', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100221, 'HepA vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100222, 'HepB vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100223, 'Hib vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100224, 'Flu vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100225, 'MMR vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100226, 'Measles vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100303, 'Rabies vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100304, 'Rotavirus vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100308, 'MCV vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100309, 'MPSV vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100227, 'Meningococcal vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100228, 'Mumps vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100229, 'Pneumo-conjugate vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100230, 'Pneumococcal polysacharide (PPSV23) vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100232, 'Polio vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100233, 'Pertussis vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100234, 'Rubella vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100310, 'Typhoid vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100236, 'Tetanus vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100311, 'Td vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100237, 'Varicella vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100312, 'Yellow Fever vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100313, 'Vaccinia (smallpox) vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100343, 'HPV', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100351, 'HZV (zoster) vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100352, 'Japanese Encephalitis vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100353, 'Lyme vaccine', 'E');
INSERT INTO event (event_id, label, event_type_code) VALUES (100212, 'flu vaccine recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100213, 'Pneumococcal polysaccharide vaccine (PPSV23) (2-64 years of age) high risk condition', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100214, 'Hepatitis A vaccine recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100215, 'Meningococcal vaccine recommended (MCV4 or MPSV4  based on age)', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100216, 'fourth dose of Hep B vaccine recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100267, 'exposed to rabies - pre-exposure Rx was completed or previous post exposure Rx was completed', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100268, 'exposed to rabies - pre-exposure Rx incomplete or unknown (needs 4 doses)', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100270, 'Zoster (shingles) Vaccine Recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100271, 'HPV Vaccine Recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100278, 'rabies Pre Exposure Prophylaxis', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100344, 'exposed to rabies - immunosuppressed', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100345, 'Hepatitis B vaccine recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100346, 'Pneumococcal conjugate vaccine (PCV13) supplemental dose (2-5 years of age)', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100347, 'Pneumococcal conjugate vaccine (PCV13) supplemental dose (6-18 years of age)', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100348, 'Pneumococcal polysaccharide vaccine (PPSV23) (2-64 years of age) very high risk condition', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100349, 'Meningococcal conjugate vaccine (MCV4 or MPSV4  based on age) prolonged exposure risk ', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100357, 'Meningococcal vaccine (MCV4 or MPSV4, based on age) high risk condition NOT asplenia or sickle cell', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100358, 'Meningococcal vaccine (MCV) new residential college student through 21 years old', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100360, 'Hib vaccine recommended - high risk condition  5 years of age and older', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100366, 'MMR vaccine - high risk (health care worker  student  traveler  international traveler) ', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100367, 'Polio vaccine (IPV) recommended', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100368, 'Tdap recommended every pregnancy between 27 - 36 weeks gestation, but may be given any time during pregnancy', 'S');
INSERT INTO event (event_id, label, event_type_code) VALUES (100369, 'Meningococcal vaccine (MCV4 or MPSV4, based on age) high risk condition, asplenia or sickle cell', 'S');

